README.md
makefile

chore: remove pluggable membrane build targets while it's not in scope

---

.github/workflows/publish.yaml

Only run version bump on PR merge.

---

pkg/plugins/document/boltdb/boltdb.go

Querying for a property that isn't present on all documents would cause the queries to fail.
Also, querying for non-string values would fail.

fix(boltdb): errors in unstructured data queries and non-strings

---

pkg/adapters/grpc/secret_grpc.go
pkg/membrane/membrane.go
pkg/plugins/secret/secret.go
pkg/plugins/secret/types.go

Base plugin interface and SDK that secret plugins will be built on. As well as adapters for gRPC secret service.

Base Secret Service Plugin

---

README.md
go.mod
go.sum
pkg/plugins/document/dynamodb/dynamodb.go
tests/plugins/document/dynamodb/dynamodb_test.go

More work required in future, but tracked in a separate issue.

fix: retrieve deployed collection names in AWS

---

go.mod
go.sum
pkg/adapters/grpc/errors.go
pkg/adapters/grpc/secret_grpc.go
pkg/plugins/secret/secret_suite_test.go
pkg/plugins/secret/secret_test.go
pkg/plugins/secret/utils.go
pkg/plugins/secret/utils_test.go

Adapter layer validation for the secret service.
Will add additional tests for entire adapter layer once mocking infrastructure from secret plugin PRs is in.

Secret GRPC Validation

---

pkg/plugins/secret/dev/dev.go

Closes: https://github.com/nitrictech/membrane/issues/141

fix: store secrets in default local share

---

pkg/plugins/document/boltdb/boltdb.go
pkg/plugins/queue/dev/queue.go
pkg/plugins/queue/dev/queue_test.go
pkg/plugins/secret/dev/dev.go
pkg/plugins/secret/dev/dev_test.go
pkg/plugins/storage/boltdb/storage.go
pkg/plugins/storage/boltdb/storage_test.go
pkg/utils/env.go
tests/plugins/document/boltdb/boltdb_test.go

closes: https://github.com/nitrictech/membrane/issues/153

fix: store dev boltdb in shared volume

---

.github/workflows/publish.yaml
.gitmodules
README.md
contracts/README.md
contracts/proto/document/v1/document.proto
contracts/proto/email/v1/email.proto
contracts/proto/event/v1/event.proto
contracts/proto/faas/v1/faas.proto
contracts/proto/queue/v1/queue.proto
contracts/proto/secret/v1/secret.proto
contracts/proto/storage/v1/storage.proto
pkg/plugins/gateway/cloudrun/http_test.go
pkg/plugins/gateway/dev/gateway_test.go
pkg/plugins/gateway/lambda/lambda.go
pkg/plugins/gateway/lambda/lambda_test.go
pkg/triggers/http_request.go
pkg/triggers/http_response.go
pkg/worker/faas_http_worker.go
pkg/worker/faas_worker.go
pkg/worker/http_worker.go

Merges contracts into the membrane, no longer using submodules to manage contracts.
Any outstanding changes to contracts will need to be cherrypicked into this repo following the merge of this change.
Contracts will be published as an archive on each release to simplify contract retrieval into dependent projects (i.e. base sdk auto generation).

Merge contracts

---

.github/workflows/release-rc.yaml

Will use the difference in merge commits between develop and main

Calculate the rc number for each dev release.

---

.githooks/pre-commit
makefile

1. where possible use "go run"
2. use make targets to prevent unnecessary "go get"

Don't keep running "go get <tool>" - it's slow

---

cmd/deploy.go
pkg/adapters/grpc/resources_grpc.go
pkg/deploy/function.go
pkg/deploy/server.go
pkg/deploy/stack.go
pkg/membrane/membrane_test.go
pkg/plugins/gateway/dev/gateway.go
pkg/utils/paths.go
pkg/worker/grpc_worker.go
pkg/worker/pool.go
tests/mocks/worker/mock.go

Adds functionality to produce an aggregrated open api spec based on declared route handlers via the FaaS API.

API Parsing

---

pkg/adapters/grpc/faas_grpc.go
pkg/membrane/membrane.go
pkg/membrane/membrane_test.go
pkg/plugins/events/dev/eventing.go
pkg/plugins/gateway/dev/gateway.go
pkg/plugins/gateway/lambda/lambda.go
pkg/plugins/queue/azqueue/azqueue.go
pkg/plugins/storage/azblob/azblob.go
pkg/providers/aws/membrane.go
pkg/providers/azure/membrane.go
pkg/providers/dev/membrane.go
pkg/providers/do/membrane.go
pkg/providers/gcp/membrane.go
pkg/worker/faas_http_worker.go
pkg/worker/grpc_worker.go
pluggable_membrane.go

This will make it easier for the cli to capture the output.

chore: Use log.Default().Print* functions instead of fmt.Print*

---

pkg/plugins/gateway/cloudrun/http.go
pkg/plugins/gateway/cloudrun/http_test.go

Fixes GCP event handling to be consistent with AWS.

Fix gcp event handling

---

go.mod
go.sum
pkg/adapters/grpc/document_grpc.go
pkg/adapters/grpc/queue_grpc.go

part of nitrictech/go-sdk#44
Once this is merged, I'll use this function utlis.NewStruct() in go-sdk.

fix: converting slice or maps of specific types (non interface)

---

tools/tools.mk

Updating uname call for getting architecture for protoc distribution.

fix builds on arch.

---

README.md

Proposing a Discord link in the contact options.

Adding Discord link in the readme text

---

pkg/plugins/gateway/lambda/lambda.go

Adds a healthcheck we can invoke during deployments to ensure that the lambda is going to work.

Add healthcheck to lambda gateway.

---

README.md

preview: https://github.com/nitrictech/nitric/tree/readme-updates

docs: fix broken build status badge.

---

cloud/gcp/deploy/config/config.go
cloud/gcp/deploy/exec/cloudrun.go
cloud/gcp/deploy/up.go

sample config:
```yaml
name: test-gcp
provider: nitric/gcp@0.0.1
region: australia-southeast1
gcp-project-id: ivory-mountain-127809
config:
custom:
cloudrun: # <-- set properties specific to cloudrun
timeout: 20
```

feat: GCP Cloudrun Config

---

cloud/aws/deploy/config/config.go
cloud/aws/deploy/up.go
cloud/azure/deploy/config/config.go
cloud/azure/deploy/up.go
cloud/common/deploy/config/config.go
cloud/common/go.mod
cloud/common/go.sum
cloud/gcp/deploy/config/config.go
cloud/gcp/deploy/up.go
go.work.sum

Use single runtime configuration key instead.

Remove 'target' from config

---

cloud/aws/mocks/provider/aws.go
cloud/aws/runtime/core/provider.go
cloud/azure/mocks/provider/azure.go
cloud/azure/runtime/core/provider.go
cloud/gcp/mocks/provider/gcp.go
cloud/gcp/runtime/core/provider.go
core/pkg/adapters/grpc/resources_grpc.go
core/pkg/providers/common/resource_plugin.go

Adds declare to the resource plugin so we can gather the resources during nitric start in CLI.

feat: add declare hook to resource plugin

---

CODEOWNERS

TODO: Determine additional owners for cloud deployment code etc.

Add global CODEOWNERS for core framework.

---

cloud/gcp/deploy/events/pubsub.go
cloud/gcp/deploy/exec/cloudrun.go
cloud/gcp/deploy/schedule/cloudscheduler.go
cloud/gcp/deploy/storage/notification.go
cloud/gcp/runtime/events/pubsub.go
cloud/gcp/runtime/gateway/http.go

see: https://cloud.google.com/appengine/docs/flexible/writing-and-responding-to-pub-sub-messages?tab=go#top

chore(gcp): Add reserved route tokens

---

README.md

preview here: https://github.com/nitrictech/nitric/tree/docs/readme

docs: add supported language and cloud links.

---

cloud/aws/deploy/up.go
cloud/azure/deploy/up.go
cloud/gcp/deploy/up.go

This reverts commit 21b6ce8999c5842b61f2504a2fc3c8990d8ee52d.
Issue was fixed by using latest pulumi docker plugin

Revert "fix: add docker:host to pulumi config to windows deploy (#517)"

---

cloud/aws/deploy/pulumiversions.go
cloud/aws/deploy/up.go
cloud/azure/deploy/pulumiversions.go
cloud/azure/deploy/up.go
cloud/common/deploy/pulumiversions.go
cloud/gcp/deploy/pulumiversions.go
cloud/gcp/deploy/up.go

TODO: Need a design for overriding versions as well.

fix: Lock provider versions

---

cloud/azure/deploy/up.go

Fixes a few issues in azure deployments. See commits for details.

fix: fixes to azure deployment

---

cloud/aws/deploy/api.go
cloud/aws/deploy/deploy.go
cloud/azure/deploy/api.go
cloud/azure/deploy/deploy.go
cloud/azure/deploy/httpproxy.go
cloud/common/deploy/provider/provider.go
cloud/common/deploy/provider/pulumi.go
cloud/gcp/deploy/deploy.go

return endpoints for API, HTTP Proxies and Websockets.

add results outputs

---

cloud/azure/deploy/api.go
cloud/azure/deploy/deploy.go
cloud/azure/deploy/httpproxy.go

Update API management auth configuration

fix(azure): upgrade az pulumi plugin and reconfigure api management auth

---

cloud/aws/deploy/service.go

Fix configuration for AWS provisioned concurrency.

fix: Aws provisioned concurrency config.

---

cloud/aws/deploy/bucket.go
cloud/aws/deploy/config.go
cloud/aws/deploy/deploy.go
cloud/aws/deploy/secret.go

Buckets must currently be in the same region as the nitric project to allow importing.

feat(aws): allow importing existing S3 buckets

---

cloud/aws/deploytf/.nitric/modules/api/main.tf
cloud/aws/deploytf/.nitric/modules/service/main.tf
cloud/aws/deploytf/deploy.go
cloud/aws/deploytf/policy.go
cloud/aws/deploytf/resources.go
cloud/common/deploy/provider/terraform.go
cloud/gcp/deploytf/deploy.go

Adds module extensions for terraform as well as direct overrides.
Also fixes image push to ensure updates are always applied when available for migration images.

fix: Terraform provider updates

---

cloud/azure/deploy/policy.go
cloud/azure/deploy/service.go

fixes #736 
Includes removal of unnecessary built in roles
[nitric-spec.json](https://github.com/user-attachments/files/19002553/nitric-spec.json)

fix(azure): prevent duplicate pulumi role assignment URNs

---

cloud/azure/common/config.go
cloud/azure/deploy/deploy.go
cloud/azure/deploy/resourcename.go
cloud/azure/deploy/website.go
cloud/azure/go.mod
cloud/azure/go.sum

Migrates from classic cdn to front door standard.
In the review double check things like cache behavior settings.

fix(azure): migrate cdn to frontdoor standard pulumi

---

cloud/aws/deploy/embeds/cloudfront.go
cloud/aws/deploy/embeds/ws-url-rewrite.js
cloud/aws/deploy/website.go

fix: Add websocket forwarding for AWS Cloudfront

---

cloud/aws/common/config.go
cloud/aws/common/resources/domain.go
cloud/aws/deploy/api.go
cloud/aws/deploy/domain.go
cloud/aws/deploy/website.go
cloud/aws/deploytf/.nitric/modules/cdn/main.tf
cloud/aws/deploytf/api.go
cloud/aws/deploytf/cdn.go
cloud/aws/deploytf/deploy.go
cloud/aws/deploytf/domain.go

Relies on base: https://github.com/nitrictech/nitric/pull/763 before merging.

feat(aws): add custom domains for pulumi and terraform websites

---

engines/terraform/plugins/awscloudfront/module/scripts/url-rewrite.js
engines/terraform/plugins/awsiamrole/module/main.tf
engines/terraform/plugins/awsiamrole/module/variables.tf

Also includes fixes to the url rewrite function.

add stack_id to aws-iam-role plugin

---

engines/terraform/plugins/awslambda/module/main.tf
server/runtime/start.go

Also revert guest application start checks to original location.

Update aws lambda naming

---

engines/terraform/plugin.go

Version will be managed via git tags

remove version from plugin manifest

---

cli/internal/simulation/simulation.go
cli/pkg/app/nitric.go

Add exit messages for dev and edit

---

cli/internal/style/colors/colors.go
cli/pkg/app/nitric.go

default `nitric init` proj name to the current dir name

---

cli/pkg/schema/entrypoint.go
cli/pkg/schema/website.go

Updates JSON tag casing from camelCase to snake_case for consistency across the project.

Updates JSON tag for entrypoints for consistency

---

cli/cmd/nitric.go
cli/internal/api/models.go
cli/internal/api/platform.go
cli/internal/api/plugin.go
cli/internal/api/teams.go
cli/internal/api/templates.go
cli/pkg/app/nitric.go

Supports the changes in: https://github.com/nitrictech/platform/pull/103

update team scoped routes
