README.md, pkg/adapters/grpc/document_grpc.go, pkg/adapters/grpc/event_grpc.go, pkg/adapters/grpc/queue_grpc.go, pkg/adapters/grpc/storage_grpc.go, pkg/adapters/grpc/utils.go, pkg/adapters/grpc/utils_test.go, pkg/plugins/document/document.go, pkg/plugins/document/document_test.go, pkg/plugins/document/dynamodb/dynamodb.go, pkg/plugins/errors.go, pluggable_membrane.go
This change is to improve client side error reporting from plugin services:
Previously:
```
Error occurred handling request GET / with function: com.example.Handler
io.grpc.StatusRuntimeException: UNKNOWN: provide non-nil key
...
```
PR changes to:
```
Error occurred handling request GET / with function: com.example.Handler
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: DocumentServer.Set: provide non-nil key
...
```
=> chore: improve client side plugin service error reporting

README.md, docs/Configuration.md, pkg/membrane/membrane.go, pkg/sdk/gateway.go, pkg/worker/pool.go
Setting MIN_WORKERS to 0 enables a 'services only' usage of the Membrane.
=> feat: support min and max worker config

go.mod, go.sum, pkg/plugins/gateway/app_platform/http.go, pkg/plugins/gateway/appservice/http.go, pkg/plugins/gateway/base_http/http.go, pkg/plugins/gateway/cloudrun/http.go, pkg/plugins/gateway/dev/gateway.go, pkg/plugins/gateway/ecs/ecs.go
Have also included refactoring increase maintainability of http base gateway plugins by allowing them to share a common base plugin, with intercepting middleware.
Middleware is very bare bones at the moment, but we can add additional functionality and richness later.
=> Fix: Http Gateways not shutting down correctly

.github/workflows/publish.yaml, makefile
Attach binaries to releases.
This will be a requirement for creating a membrane build pack, but is also generally a good idea for us to be doing anyway.
=> Binary releases

.github/workflows/publish.yaml
Fixes add_binaries job
┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1dyn92q) by [Unito](https://www.unito.io)
=> ci: Add GOPATH to binary build job & fix setup-go action.

.github/workflows/generate-sdks.yaml
Trigger SDK generation on release publish.
> This depends on: https://github.com/nitrictech/base-sdk/pull/5 and remaining sdk generation branches.
=> Trigger API client generation

pkg/adapters/grpc/faas_grpc.go, pkg/worker/route_worker.go
Preserving API name metadata for route workers. This will allow us to do named API sub routing in single membrane gateway scenarios e.g. nitric run.
=> Preserve API name as part of route worker and make it readable.

pkg/worker/pool.go
This lets us get all workers when running locally and retrieving all subscribers for an event.
=> feat: allow getting all matching workers from pool

pkg/membrane/defaults.go, pkg/membrane/membrane.go, pkg/providers/aws/membrane.go, pkg/providers/azure/membrane.go, pkg/providers/dev/membrane.go, pkg/providers/do/membrane.go, pkg/providers/gcp/membrane.go
Enable starting embedded membrane in cli without a child process
=> Externalise default child process default into provider entrypoints

pkg/worker/pool.go
shortening polling time to prevent throttling on serverless runtimes like AWS lambda during cold starts.
=> Shorten and simplify worker polling

pkg/plugins/events/dev/eventing.go
This line wasn't printing nicely during a local run. If we add this back in, it should be more intentional and useful for developers.
=> fix: remove debug output for local events

pkg/plugins/document/document.go
=> fix: typo in document expressions - potential out of bounds index

pkg/plugins/document/boltdb/boltdb.go, pkg/plugins/document/document.go
Changed the subcollection delimiter to be + instead of _ as this is much less common as an id format than _.
Fixes #249 
Confirmed that the bug occurred with the same tests for the unaltered membrane.
Then to confirm the change fixed this bug, used [BloomRPC](https://github.com/bloomrpc/bloomrpc) with the local membrane to do tests for getting, setting, and deleting documents. Then tested with a local nitric run by pointing the CLI membrane plugins to my local membrane plugins and performing get, set, and delete against the collection.
=> feat: change subcollection delimiter

.github/workflows/publish-binaries.yaml
forgot to update the binary release actions with the provider->cloud rename.
=> ci: fix binary releases.

cloud/gcp/deploy/events/pubsub.go
Closes: https://github.com/nitrictech/nitric/issues/393
Relevant docs: https://www.pulumi.com/registry/packages/gcp/api-docs/pubsub/subscription/#subscriptionexpirationpolicy
=> feat: remove expiry on subscriptions for gcp

.github/workflows/test.yaml, cloud/aws/deploy/config/config.go, cloud/azure/deploy/config/config.go, cloud/azure/deploy/exec/containerapp.go, cloud/azure/deploy/up.go, cloud/common/deploy/config/config.go, cloud/gcp/deploy/config/config.go
Adds azure config, note `memory` config for azure container apps can only be done in gigabytes, so it will differ from the other cloud memory configs (want the config to be closer to the actual cloud rather than perform arbitrary conversions).
=> feat: Azure config

cloud/gcp/Makefile, cloud/gcp/deploy/events/pubsub.go, cloud/gcp/deploy/exec/cloudrun.go, cloud/gcp/deploy/queue/pubsub.go, cloud/gcp/deploy/up.go, cloud/gcp/ifaces/pubsub/adapters.go, cloud/gcp/ifaces/pubsub/ifaces.go, cloud/gcp/mocks/pubsub/mock.go, cloud/gcp/runtime/events/pubsub.go, cloud/gcp/runtime/events/pubsub_test.go, cloud/gcp/runtime/gateway/http.go, cloud/gcp/runtime/queue/pubsub.go
Closes #416
- Adds name resolution to GCP topics (includes queues). This will stop conflicts when deploying the same project to GCP twice. 
- Stop queues expiring after 31 days of inactivity
=> feat: add name resolution for GCP topics and queues

cloud/aws/deploy/config/config.go, cloud/aws/deploy/secret/secretsmanager.go, cloud/aws/deploy/up.go, cloud/aws/runtime/secret/secrets_manager.go
Example config
```yaml
name: test-aws
provider: nitric/aws@0.0.1
region: ap-southeast-2
import:
secrets:
test: <your_secrets_arn>
```
Behaviours:
- If you add an import over an existing nitric secret, that secret will be deleted and replaced by the imported secret.
- If you remove an imported secret that secret will not be deleted, but a new nitric secret will be created to take its place.
- Imported secrets will be tagged as part of the deployment process. With essential nitric tags
- If an imported secret cannot be located, deployment will fail.
=> feat(aws): allow existing secret import

cloud/aws/runtime/gateway/lambda.go, cloud/aws/runtime/gateway/lambda_test.go
Ensure that messages flagged as unsuccessful are properly rejected.
=> fix: AWS SNS failure

cloud/aws/deploy/config/config.go, cloud/aws/deploy/up.go, cloud/azure/deploy/config/config.go, cloud/azure/deploy/up.go, cloud/gcp/deploy/config/config.go, cloud/gcp/deploy/up.go
Setting this flag to true will get stacks to refresh from existing infrastructure
e.g.
```yaml
name: test-aws
provider: nitric/aws@0.0.1
region: ap-southeast-2
refresh: true
```
=> fix: Add refresh flag to providers

cloud/aws/deploy/config/config.go, cloud/aws/deploy/exec/lambda.go, cloud/azure/deploy/config/config.go, cloud/gcp/deploy/config/config.go
Proposal for adding VPC configuration for AWS Lambda to aws stack configuration:
```yaml
name: example-aws
provider: nitric/aws@0.28.0
region: us-east2
config:
database-access:
lambda:
vpc:
security-group-ids:
- example-id
subnet-ids:
- example-id
```
This should allow lambdas deployed with nitric to access existing resources within VPCs.
=> feat: AWS Lambda VPC config

cloud/azure/deploy/exec/containerapp.go, cloud/azure/deploy/schedule/dapr.go, cloud/azure/deploy/up.go, cloud/azure/go.mod, cloud/azure/go.sum, cloud/azure/runtime/gateway/http.go
Need to determine scaling rules with the application to get this style of scheduling working consistently.
Currently once the app has scaled to zero events will no longer be sent.
Need to define some [KEDA cron scale rules](https://keda.sh/docs/2.10/scalers/cron/) in future to scale up prior to schedule fireing and to scale down after as well. For now containerapps that contain schedules will have their minimum replicas set to 1.
=> feat: Azure Schedules

cloud/aws/deploy/up.go, cloud/azure/deploy/up.go, cloud/gcp/deploy/up.go
On windows 10 docker, the protocol is not available when using nitric up.
The fix sets the docker host to "npipe:////.//pipe//docker_engine" on windows only. As seen here: https://github.com/pulumi/pulumi/issues/8626
Needs testing.
Fixes # (issue)
=> fix: add docker:host to pulumi config to windows deploy

cloud/aws/deploy/exec/lambda.go, cloud/aws/deploy/up.go
Just ran into this developing a provider. Was unable to properly inject external environment variables from other Pulumi deployed resources.
=> fix: make lambda exec unit resource more reusable.

cloud/aws/deploy/api/apigateway.go
Co-authored-by: Tim Holm <tim.holm@nitric.io>
=> fix: issue causing missing api gateway tags on first deploy

README.md, cloud/common/deploy/config/config.go, cloud/gcp/cmd/runtime/README.md, cloud/gcp/runtime/gateway/http_test.go, core/contracts/validate/validate.proto, core/pkg/proto/deployments/v1/deployments.pb.go, docs/Configuration.md, docs/Operating-Modes.md, nitric/proto/deployments/v1/deployments.proto
Shared this link with my coworkers and then noticed that privilege is
spelled wrong on the front page. Ran `codespell` on the
repo and fixed accordingly.
Include a summary of the change or which issue is fixed. Please also include any relevant context including any dependencies that are required for this change.
Fixes spelling
I don't know for sure, but I _think_ this requires a documentation update
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
No code was updated, no tests were run.
=> chore: spelling

cloud/common/deploy/image/image.go, core/pkg/env/variables.go, core/pkg/membrane/membrane.go
Add WORKER_TIMEOUT to allow for the configuration of nitric gateway timeout when waiting for workers to connect.
=> fix: Add env variable to worker timeout configuration.

cloud/common/deploy/provider/dependencies.go, cloud/common/deploy/provider/pulumi.go
=> fix: Add dependency check for pulumi providers.

cloud/aws/runtime/resource/resource.go
Might be better to limit the fallout of this error to just the specific resource that's duplicated - this currently impacts all resources.
Happy to make that change if we think it's better, it'll just take bit more work. Trade off is if the duplicate resource is rarely used it could go unnoticed for a while without detection.
=> fix: return an explicit error when duplicate resources are found

cloud/gcp/deploy/project.go
I am assuming based on the documentation we should be activating the correct services for GCP for API Gateway. I couldn't from a fresh nitric project generation access the API Gateway dashboard as we are missing dependant services not being applied during the nitric up command.
- fixes https://github.com/nitrictech/nitric/issues/658
- [Link to docs - api gateway and cloud run](https://cloud.google.com/api-gateway/docs/get-started-cloud-run)
Not sure how to test and run the project <---- needs a second pair of eyes :)
=> fix: add missing gcp api gateway services to gcp cloud project.go

cloud/aws/common/config.go, cloud/aws/deploy/batch.go
Adds configuration for block device mapping:
```yaml
batch-compute-env:
min-cpus: 0
max-cpus: 4
instance-types:
- g5
- optimal
launch-template:
block-device-mappings:
- device-name: /dev/xvda
ebs:
volume-size: 20
volume-type: gp2
delete-on-termination: "true"
```
Will allow configuration of larger default system volume sizes.
In future we may want to consider configuring volume/bucket mounts for batch/services
=> fix(aws/batch): Add config for increasing docker system volume size via launch template

cloud/aws/deploy/deploy.go, cloud/azure/deploy/deploy.go
Add resource group links to output of `nitric up` for AWS and Azure
=> fix: Add resource group links to output

cloud/aws/deploy/batch.go, cloud/aws/deploy/service.go, cloud/azure/deploy/service.go, cloud/azure/deploy/sql.go, cloud/common/deploy/image/image.go, cloud/common/deploy/provider/dependencies.go, cloud/common/deploy/provider/pulumi.go, cloud/gcp/deploy/batch.go, cloud/gcp/deploy/service.go
We previously checked specifically for the docker binary on path, but we only interact with the API. Since Podman offers a compatible API, removing the binary check allows podman to work with all nitric providers when it's in docker compatibility mode.
=> fix: podman support for all core providers

cloud/aws/cmd/runtime/main.go, cloud/aws/common/index.go, cloud/aws/deploy/deploy.go, cloud/aws/deploy/resources.go, cloud/aws/deploy/schedule.go, cloud/aws/deploytf/service.go, cloud/aws/go.mod, cloud/aws/go.sum, cloud/aws/mocks/provider/aws.go, cloud/aws/runtime/env/variables.go, cloud/aws/runtime/gateway/lambda_test.go, cloud/aws/runtime/gateway/router.go, cloud/aws/runtime/resource/resource.go, cloud/aws/runtime/resource/resource_test.go, cloud/aws/runtime/resource/ssm.go
Updates nitric resource lookup to use SSM parameters instead of the resourcetaggingapi.
=> fix: AWS resource lookup

cloud/aws/runtime/api/api.go, cloud/azure/runtime/api/api.go, cloud/gcp/runtime/api/api.go
Required rename, caused a non implemented error when using the url method on an api resource.
=> fix: issue retrieving api runtime url

cloud/aws/deploy/api.go, cloud/aws/deploytf/api.go
This error can't occur with standard nitric providers, but catching it helps with custom providers that may edit the API spec before generating the AWS specific spec.
Currently this panics with a invalid memory address or nil pointer dereference error message, which makes it unclear what went wrong.
=> fix(aws): improve the error if an undefined service is declared in APIs

cloud/common/deploy/env/variables.go, cloud/common/deploy/provider/terraform.go
Instead, moving to a note about reviewing the generated outputs before deployment.
=> fix: remove beta-providers preview flag

cloud/aws/runtime/storage/s3.go, cloud/azure/runtime/storage/azblob.go, cloud/azure/runtime/storage/azblob_test.go, cloud/common/runtime/storage/storage.go, cloud/gcp/ifaces/gcloud_storage/adapter.go, cloud/gcp/ifaces/gcloud_storage/iface.go, cloud/gcp/mocks/gcp_storage/mock.go, cloud/gcp/runtime/storage/storage.go, cloud/gcp/runtime/storage/storage_test.go
Apply the same content-type detection scheme to all supported clouds
=> fix(storage): consistently detect and store content-type when writing files

cloud/azure/deploy/topic.go, cloud/azure/deploytf/.nitric/modules/topic/main.tf
When topic names are long they result in subscriptions names that must be truncated (to max 24 chars) to meet Azure's name restrictions. The truncation could result in two services subscribing to the same topic ending up with the same name for their subscriptions, causing a conflict for the Event Subscription resources.
=> fix(azure): prevent conflicting topic subscription names

cloud/azure/deploytf/policy.go
Ensures uniqueness of policy names by including the resource name in the generated name.
Fixes #792
=> fix(azure-tf): adds resource name to policy name

cloud/aws/.goreleaser.tf.yaml, cloud/aws/.goreleaser.yaml, cloud/azure/.goreleaser.tf.yaml, cloud/azure/.goreleaser.yaml, cloud/gcp/.goreleaser.tf.yaml, cloud/gcp/.goreleaser.yaml
This small PR migrates the deprecated `changelog.skip` to `changelog.disable`:
```
DEPRECATED:  changelog.skip should not be used anymore, check https://goreleaser.com/deprecations#changelogskip for more info
```
see [CI logs](https://github.com/nitrictech/nitric/actions/runs/14790378366/job/41526191924#step:5:46) for more information.
=> ci: migrate to changelog.disable

cloud/gcp/deploy/deploy.go, cloud/gcp/deploy/website.go
Currently a domain configuration is always being checked, but it's only required when websites are enabled.
=> fix(gcp): only require a domain when websites are deployed

server/runtime/service/proxy.go
This will allow direct reverse proxy implementation in plugins rather than double handling the request.
=> Add Host method to service proxy

cloud/aws/deploy/api.go, cloud/aws/deploy/domain.go, cloud/aws/deploy/website.go
- Adds aliases to various domain related resources (dns records, certificate, etc.) to ensure Pulumi correctly identifies previously deployed resources and doesn't replace them.
- Fixes a bug when deploying APIs with custom domains to regions other that us-east-1
=> fix(aws): fix backward compatibility of aws custom domain deployments

cli/internal/simulation/simulation.go, cli/pkg/schema/entrypoint.go, engines/terraform/plugins/awscloudfront/module/main.tf, engines/terraform/plugins/awscloudfront/module/variables.tf, engines/terraform/terraform.go
Allows subsets of application routes to be exposed via the entrypoints. This will be important for when we implement triggers so their routes can be kept clear of the main entrypoint.
=> Add base path routing to entrypoints

cli/cmd/nitric.go, cli/cmd/root.go, cli/pkg/app/nitric.go, cli/pkg/tui/errors.go, cli/pkg/tui/select.go, cli/pkg/tui/textinput.go, cli/pkg/tui/toggle.go
The init command allows a user to start a new nitric project from scratch or within an existing application repository.
Closes: NIT-63
https://github.com/user-attachments/assets/7be3aa10-3752-4d10-a3fe-f86be61b5654
https://github.com/user-attachments/assets/7356fccc-69ec-43d9-81c2-d67833175e57
=> add an init command to the new cli

cli/internal/version/version.go, cli/pkg/app/nitric.go
When using an alias to point at the binary file for the CLI the os.Args[0] value is a full path e.g. `/Users/you/somewhere/nitric/cli/bin/nitric`. If there is a clever way to get around this I'm open to it. Otherwise, simplicity is probably the solution and we just use a string.
Before:
After:
=> fix fullpath showing instead of cli binary name

cli/cmd/auth.go, cli/internal/api/api.go, cli/internal/workos/workos.go, cli/pkg/app/auth.go
Allows you to force a refresh of your access token, useful for testing when permissions have been updated to save a login/logout
=> add --refresh option to access-token cmd

engines/terraform/backend.go, engines/terraform/terraform.go
The default backend was preventing users from defining their own backend.tf file inline with generated terraform. This should now be possible as we will never generate a default backend as part of out terraform output.
=> Remove the default backend from out terraform output.

cli/internal/simulation/service/service.go
=> stop restarts in case of consecutive fast crashes

cli/pkg/schema/database.go, cli/pkg/schema/validate.go, engines/terraform/deployment.go, engines/terraform/resolve.go, engines/terraform/resource_handler.go, engines/terraform/terraform.go, engines/terraform/variables.go
also includes a crude breakup of the current apply function. Still needs more refactoring to increase test-ability.
=> Add support for specifying a env_var_key as part of a database definition

cloud/aws/deploy/deploy.go, cloud/aws/deploy/service.go, cloud/common/deploy/provider/options.go, cloud/common/deploy/provider/pulumi.go, cloud/common/deploy/pulumix/clistream.go
Enhances the stability and reliability of the deployment process:
- Introduces a timeout mechanism for stack ID retrieval to prevent indefinite blocking.
- Adds error handling during AWS resource group creation.
- Logs previously unhandled stream errors from Pulumi.
- Provides more context to Pulumi stream send errors.
- Removes the unused error handlers option.
These changes address potential issues during deployment and improve overall error reporting.
=> fix(aws): improves error handling and stack ID retrieval

docs/contentlayer.config.ts, docs/docs/misc/comparison/ampt.mdx, docs/docs/misc/comparison/aws-cdk.mdx, docs/docs/misc/comparison/aws-sam.mdx, docs/docs/misc/comparison/bicep.mdx, docs/docs/misc/comparison/encore.mdx, docs/docs/misc/comparison/gcp-deployment-manager.mdx, docs/docs/misc/comparison/pulumi.mdx, docs/docs/misc/comparison/sst.mdx, docs/docs/misc/comparison/terraform.mdx, docs/src/app/(sitemaps)/sitemap-0.xml/route.ts, docs/src/app/[[...slug]]/page.tsx, docs/src/app/robots.ts
Hides comparison documentation pages from search engine indexing and the sitemap.
This prevents these pages from appearing in search results.
The changes include:
- Adding a `noindex` field to the contentlayer configuration
- Setting `noindex: true` in the frontmatter of comparison MDX documents
- Updating the sitemap generation to exclude comparison pages
- Adding a disallow rule to the robots.txt for the `/misc/comparison/` path
Closes NIT-11
=> docs: excludes comparison docs from search indexing
